services:

  db:
    container_name: 'my_pg_container'
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cleaning
    ports:
      - '5432:5432'
    networks:
      - custom

  pgadmin:
    container_name: my_pg_admin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - custom

networks:
  custom:
    driver: bridge